// <auto-generated />
using System;
using CyberSOC.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberSOC.Persistence.Migrations
{
    [DbContext(typeof(CyberSocDbContext))]
    partial class CyberSocDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberSOC.Domain.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlertType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("UserId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("_evidenceEventIds")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EvidenceEventIds");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAt")
                        .HasDatabaseName("IX_Alerts_RaisedAt");

                    b.HasIndex("SourceIp")
                        .HasDatabaseName("IX_Alerts_SourceIp");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Alerts_Status");

                    b.ToTable("Alerts", (string)null);
                });

            modelBuilder.Entity("CyberSOC.Domain.Entities.SecurityEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Attributes");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("TargetResource")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .HasDatabaseName("IX_SecurityEvents_Timestamp");

                    b.ToTable("SecurityEvents", (string)null);
                });

            modelBuilder.Entity("CyberSOC.Domain.ThreatIntel.IndicatorOfCompromise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Confidence")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<DateTimeOffset>("LastSeen")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tags")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Indicators");
                });

            modelBuilder.Entity("CyberSOC.Domain.Entities.SecurityEvent", b =>
                {
                    b.OwnsOne("CyberSOC.Domain.ValueObjects.NetworkActor", "Actor", b1 =>
                        {
                            b1.Property<Guid>("SecurityEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("CountryCode")
                                .HasMaxLength(2)
                                .HasColumnType("nvarchar(2)")
                                .HasColumnName("ActorCountryCode");

                            b1.Property<string>("DeviceFingerprint")
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)")
                                .HasColumnName("ActorDeviceFingerprint");

                            b1.Property<string>("IpAddress")
                                .IsRequired()
                                .HasMaxLength(45)
                                .HasColumnType("nvarchar(45)")
                                .HasColumnName("ActorIp");

                            b1.Property<string>("UserAgent")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)")
                                .HasColumnName("ActorUserAgent");

                            b1.Property<string>("UserId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("ActorUserId");

                            b1.HasKey("SecurityEventId");

                            b1.ToTable("SecurityEvents");

                            b1.WithOwner()
                                .HasForeignKey("SecurityEventId");
                        });

                    b.Navigation("Actor")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
